{"name": "Проверка регистрации нового пользователя с невалидными данными", "status": "passed", "steps": [{"name": "Проверка статус-кода", "status": "passed", "steps": [{"name": "Создание пользователя", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://5.63.153.31:5051/v1/account\n", "trace": "  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\helpers\\account_helper.py\", line 42, in create_user\n    response_login = self.dm_account_api.account_api.post_v1_account(registration=registration)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\dm_api_account\\apis\\account_api.py\", line 22, in post_v1_account\n    response = self.post(\n        path='/v1/account',\n        json=registration.model_dump(exclude_none=True, by_alias=True)\n    )\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\client.py\", line 30, in post\n    return self.send_request(method='POST', path=path, **kwargs)\n           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\utilities.py\", line 15, in wrapper\n    response = fn(*args, **kwargs)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\client.py\", line 67, in send_request\n    rest_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "Регистрация пользователя", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://5.63.153.31:5051/v1/account\n", "trace": "  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\dm_api_account\\apis\\account_api.py\", line 22, in post_v1_account\n    response = self.post(\n        path='/v1/account',\n        json=registration.model_dump(exclude_none=True, by_alias=True)\n    )\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\client.py\", line 30, in post\n    return self.send_request(method='POST', path=path, **kwargs)\n           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\utilities.py\", line 15, in wrapper\n    response = fn(*args, **kwargs)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\client.py\", line 67, in send_request\n    rest_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "attachments": [{"name": "request_body", "source": "33b246d3-a64c-49a5-bd74-0c6990c4c76f-attachment.json", "type": "application/json"}], "parameters": [{"name": "registration", "value": "Registration(login='validlogin17', password='validPass123', email='invalidemail.com')"}], "start": 1757086059142, "stop": 1757086059379}], "parameters": [{"name": "login", "value": "'validlogin17'"}, {"name": "password", "value": "'validPass123'"}, {"name": "email", "value": "'invalidemail.com'"}], "start": 1757086059142, "stop": 1757086059387}], "start": 1757086059142, "stop": 1757086059394}], "attachments": [{"name": "stdout", "source": "b34438d1-24d2-4406-ba15-73ebc90734c7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login", "value": "'validlogin17'"}, {"name": "email", "value": "'invalidemail.com'"}, {"name": "password", "value": "'validPass123'"}, {"name": "expected_status_code", "value": "400"}, {"name": "error_message", "value": "'Validation failed'"}], "start": 1757086059142, "stop": 1757086059396, "uuid": "a29e105c-f2d5-4f0a-bf6b-3f7184727d20", "historyId": "51e604b4476c60cf918ee9418b8ef147", "testCaseId": "f9166e14fd5f64c33668176043bcf5f0", "fullName": "tests.functional.post_v1_account.test_post_v1_account.TestsPostV1Account#test_post_v1_account_negative", "labels": [{"name": "subSuite", "value": "Позитивный и негативный тесты POST v1/account"}, {"name": "suite", "value": "Тесты на проверку метода POST v1/account"}, {"name": "parentSuite", "value": "tests.functional.post_v1_account"}, {"name": "host", "value": "ASUSVivoBook"}, {"name": "thread", "value": "14232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.functional.post_v1_account.test_post_v1_account"}], "titlePath": ["tests", "functional", "post_v1_account", "test_post_v1_account.py", "TestsPostV1Account"]}