{"name": "Проверка регистрации нового пользователя с невалидными данными", "status": "passed", "steps": [{"name": "Проверка статус-кода", "status": "passed", "steps": [{"name": "Создание пользователя", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://5.63.153.31:5051/v1/account\n", "trace": "  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\helpers\\account_helper.py\", line 42, in create_user\n    response_login = self.dm_account_api.account_api.post_v1_account(registration=registration)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\dm_api_account\\apis\\account_api.py\", line 22, in post_v1_account\n    response = self.post(\n        path='/v1/account',\n        json=registration.model_dump(exclude_none=True, by_alias=True)\n    )\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\client.py\", line 30, in post\n    return self.send_request(method='POST', path=path, **kwargs)\n           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\utilities.py\", line 15, in wrapper\n    response = fn(*args, **kwargs)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\client.py\", line 67, in send_request\n    rest_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "Регистрация пользователя", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://5.63.153.31:5051/v1/account\n", "trace": "  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\dm_api_account\\apis\\account_api.py\", line 22, in post_v1_account\n    response = self.post(\n        path='/v1/account',\n        json=registration.model_dump(exclude_none=True, by_alias=True)\n    )\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\client.py\", line 30, in post\n    return self.send_request(method='POST', path=path, **kwargs)\n           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\utilities.py\", line 15, in wrapper\n    response = fn(*args, **kwargs)\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\restclient\\client.py\", line 67, in send_request\n    rest_response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\JetBrains\\Projects PyCharm\\dm_api_tests\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "attachments": [{"name": "request_body", "source": "5795019b-c1c3-4cdb-a6a9-3574fe68ffb6-attachment.json", "type": "application/json"}], "parameters": [{"name": "registration", "value": "Registration(login='validlogin16', password='123', email='user16@example.com')"}], "start": 1757086058900, "stop": 1757086059115}], "parameters": [{"name": "login", "value": "'validlogin16'"}, {"name": "password", "value": "'123'"}, {"name": "email", "value": "'user16@example.com'"}], "start": 1757086058900, "stop": 1757086059119}], "start": 1757086058900, "stop": 1757086059122}], "attachments": [{"name": "stdout", "source": "9d5a22b1-e839-41bf-a7f1-1a9fca8bba95-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login", "value": "'validlogin16'"}, {"name": "email", "value": "'user16@example.com'"}, {"name": "password", "value": "'123'"}, {"name": "expected_status_code", "value": "400"}, {"name": "error_message", "value": "'Validation failed'"}], "start": 1757086058900, "stop": 1757086059123, "uuid": "834a87fb-0bc0-4d10-8170-f29c58eaba24", "historyId": "6bb88c6ac1bc3f7a24952d70b1049bc2", "testCaseId": "f9166e14fd5f64c33668176043bcf5f0", "fullName": "tests.functional.post_v1_account.test_post_v1_account.TestsPostV1Account#test_post_v1_account_negative", "labels": [{"name": "subSuite", "value": "Позитивный и негативный тесты POST v1/account"}, {"name": "suite", "value": "Тесты на проверку метода POST v1/account"}, {"name": "parentSuite", "value": "tests.functional.post_v1_account"}, {"name": "host", "value": "ASUSVivoBook"}, {"name": "thread", "value": "14232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.functional.post_v1_account.test_post_v1_account"}], "titlePath": ["tests", "functional", "post_v1_account", "test_post_v1_account.py", "TestsPostV1Account"]}